### ISSUE TITLE
Follow/Unfollow

### ISSUE THREAD

**Issue by aronprins** [yemaw/StaticIGBot#1]
Love this tool! Is there a way to build in follow/unfollow users?
Let me know if possible and what price tag if required ;)

Cheers,
Aron

**Comment by yemaw** [comment]
Hi @aronprins , currently it only works for find images by tag and liking them automatically. will try to add follow/unfollow features. :)

**Comment by aronprins** [comment]
Email me at: pwf.aron@gmail.com and lets discuss. I might have an interesting proposal for you ;)

Cheers,
Aron
